<center>Слайдеры:</center>
<a href="/admin/?inc=slider">Слайдер на главной</a>
<hr>
<center>Галереи:</center>
<a href="/admin/?inc=interiors">Интерьеры</a>
<a href="/admin/?inc=plans">Ход строительства</a>
<a href="/admin/?inc=pents">Пентхаусы</a>
<hr>
<center>Модули:</center>
<a href="/admin/?inc=apartment">Модуль Квартир</a>
<a href="/admin/?inc=uploader">Загр. Документов</a>
<a target="_blank" href="/admin/kcfinder/browse.php?type=files&CKEditor=ta&CKEditorFuncNum=3&langCode=ru">Загр. файлов </a>
<hr>